### ISSUE TITLE
Gradle Sync Issues

### ISSUE THREAD

**Issue by brandonwicks** [SiliconLabs/EFRConnect-android#10]
I'm trying to compile this software with the latest version of Android Studio 3.5.1, I installed all the dependencies during project import.  Once everything was installed, I get the following ERROR: Could not find com.android.support:appcompat-v7:22.2.1.
Required by:
    project :mobile
    project :mobile > project :libraries:materialdesign
Search in build.gradle files

I searched in the Android SDK platform packages but there isn't any Android Support packages to enable & download.

Does anyone know how to fix this?

Thanks,
Brandon

**Comment by nitish3072** [comment]
Facing the same issue.

**Comment by silabs-tiago** [comment]
Can you please try out with the latest version 1.5.1 and let us know if you are still facing the same problem.
