### ISSUE TITLE
Connection Interval limited

### ISSUE THREAD

**Issue by wher0001** [SiliconLabs/EFRConnect-android#11]
The connection interval settings should be allowed to go to max of the spec.
This is how many people are gong to use the IoT device in the field to save battery power.

When I set it to High Priority in the app (100ms - 125ms) I get 360 ms using the energy profiler.
This would need to go to 4 secs as the BLE spec suggests.

**Comment by silabs-tiago** [comment]
This a limitation of the underlying Android API, not EFR Connect app.
https://developer.android.com/reference/android/bluetooth/BluetoothGatt.html#requestConnectionPriority(int)

On our test we have observed that the connection interval changes according to what is requested by the user in EFR Connect. If you observe something else then please create a post on our community and our support teams can help throubleshooting this.
