### ISSUE TITLE
OTA example application

### ISSUE THREAD

**Issue by ozanerturk** [SiliconLabs/EFRConnect-android#14]
Hi! Really thanks for this application.  Great work!
We were trying to do OTA firmware updates and I spent so much time while reading your code,  there was so much stuff going in your application so I created an example application that just implements OTA progress. I tried to keep the code clean and simple and wrote some inline comments to help the reader. I am leaving a link to the example applications here so if there are any other people trying to implement OTA, I think it will be easier to understand what is going on. 

Thanks!
https://github.com/sensemore/slilabs-ota

**Comment by silabs-tiago** [comment]
Thanks a lot for this.
