### ISSUE TITLE
A variant version, UI improved by me, please try

### ISSUE THREAD

**Issue by RadioOperator** [SiliconLabs/EFRConnect-android#15]
I'm frequently using EFR Connect, to make me easy and effective, I've modified the source.
Please visit
https://github.com/RadioOperator/EFRConnect-android-variant
Thanks.

**Comment by silabs-TiagoM** [comment]
Thanks for this, some interesting ideas, we will consider incorporating them into the main app.

**Comment by RadioOperator** [comment]
@silabs-TiagoM  Hi,
I tried send you my code to tiago.monte@silabs.com, but not reachable.
Thanks.
