### ISSUE TITLE
The new v2.3.0 - Bluetooth standard characteristics cannot auto-display

### ISSUE THREAD

**Issue by RadioOperator** [SiliconLabs/EFRConnect-android#17]
Hi, refer to attached pic, the new version v2.3.0 is not good.
Thanks.
![Screenshot_20210629](https://user-images.githubusercontent.com/27762920/123737692-00072000-d8d6-11eb-8acd-caeffc9f5621.jpg)

**Comment by silabs-TiagoM** [comment]
Hi,

Yes we are aware of this issue and it will be corrected on a coming patch.
