### ISSUE TITLE
Does it support mesh topology?

### ISSUE THREAD

**Issue by TanwaiSS** [SiliconLabs/EFRConnect-android#6]

**Comment by silabs-tiago** [comment]
Hi,

No, this is only for BLE. For BT Mesh we have a separate app: https://play.google.com/store/apps/details?id=com.siliconlabs.bluetoothmesh&hl=en

The source code for this app can be found in the BT Mesh ADK which can be downloaded via Simplicity Studio: https://www.silabs.com/community/software/simplicity-studio

Regards,
Tiago
