### ISSUE TITLE
The latest production app crashes every time the Bluetooth Browser is tapped

### ISSUE THREAD

**Issue by justynspooner** [SiliconLabs/EFRConnect-android#7]
Have just downloaded the latest Android Play Store app (version released: 24th April 2018)

Tap on Bluetooth Browser and the app crashes.

Crash occurs on all the following devices:
Samsung Galaxy S7 Edge Android 8.0.0
Samsung Galaxy S6 Android 7.0
Samsung Galaxy S5 Android 6.0.1

I've just tested in an environment without any other Bluetooth devices apart from the Silicon Labs board and the app does not crash. When I move back into an environment with other Bluetooth devices, the app starts crashing again.

**Comment by silabs-tiago** [comment]
Hi,

Have you tried other apps on the environment that induces the crash (e.g. nRF, Lightblue)? We have never seen this crash occur at our office where there is a lot of Bluetooth traffic.

Regards,
Tiago
