### ISSUE TITLE
BLE Mesh 

### ISSUE THREAD

**Issue by sundharsk** [SiliconLabs/EFRConnect-android#9]
Can you share the BLE Mesh app  android source code(java)

**Comment by silabs-tiago** [comment]
The Bluetooth Mesh app source code is distributed as part of the Bluetooth Mesh ADK which you install via Simplicity Studio package manager.

**Comment by sundharsk** [comment]
@silabs-tiago  I know that  but the source code was there in kotlin language . Are you having the code in java format

**Comment by silabs-tiago** [comment]
No, it's in kotlin

**Comment by sundharsk** [comment]
okay thanks for your response :-)
